# Generated by Django 4.0.6 on 2023-01-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emojis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
